services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: teamway-app
        restart: unless-stopped
        working_dir: /var/www
        ports:
            - "8181:8181"
        environment:
            - APP_ENV=production
            - APP_URL=https://teamway.silentreactive.my.id
            - VITE_APP_URL=https://teamway.silentreactive.my.id
            - APP_NAME=Teamway
        networks:
            - teamway-net

networks:
    teamway-net:
        driver: bridge
